name: create_conda_package
on:
  push:
    branches: [master, condaWorkflowTests]
  label:
    types: [created, edited]


jobs:
  linux:
    if: github.repository=='JanNiklasB/CRPropa3'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Preinstall
        run: |
          ldd --version
          conda init
          conda update -n base conda -y
          conda install conda-build -y
      - name: Build Conda Package
        env:
          accountName: ${{ secrets.ANACONDA_ACCOUNTNAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda init
          conda activate base
          cd conda-bld
          conda config --set anaconda_upload yes
          conda build -m conda_build_config.yaml -c conda-forge . \
            --user $accountName \
            --token $token
