name: create_conda_package
on:
  push:
    branches: [master, condaWorkflowTests]
  label:
    types: [created, edited]


jobs:
  linux:
    if: github.repository=='JanNiklasB/CRPropa3'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Preinstall
        run: |
          ldd --version
          conda init $> /dev/null
          echo update -n base conda ...
          conda update -n base conda -y &> /dev/null
          echo   Finished updating conda!
          echo install conda-build anaconda anaconda-client ...
          conda install conda-build anaconda anaconda-client -y &> /dev/null
          echo   Finished installing!
      - name: Build Conda Package
        env:
          accountName: ${{ secrets.ANACONDA_ACCOUNTNAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          set -ex
          conda init $> /dev/null
          cd conda-bld
          conda config --set anaconda_upload yes 
          conda build -m conda_build_config.yaml -c conda-forge . \
            --user $accountName \
            --token $token \
            | tee build.log
      - name: Archive Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "Anaconda_Build_Log"
          path: conda-bld/build.log