name: crpropa-testing_ubuntu22
on: [push, pull_request]

jobs:
  linux:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
         - name: "ubuntu-22"
           os: ubuntu-22.04
           cxx: "g++"
           cc: "gcc"
           fc: "gfortran"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Preinstall
        run: |
          sudo apt-get update
          sudo apt-get install gfortran g++ gcc cmake libmuparser-dev libhdf5-serial-dev libomp5 libomp-dev libfftw3-dev libcfitsio-dev lcov ninja-build -y
      - name: Set up the build
        env:
          CXX: ${{ matrix.config.cxx }}
          CC: ${{ matrix.config.cc }}
          FC: ${{ matrix.config.fc }}
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DENABLE_PYTHON=False -DENABLE_TESTING=On -DSIMD_EXTENSIONS=native
      - name: Build CRPropa
        run: |
          cd build
          cmake --build .
      - name: Run tests
        run: |
          cd build
          ./testInteraction
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "test-report_${{matrix.config.name}}"
          path: build/Testing/Temporary/LastTest.log
  